- resources:
    cpu: true
    memory: true
    cputemp: true
    units: metric
    network: true
    disk: true

- datetime:
    label: Tienen, BE
    timezone: Europe/Brussels
    locale: nl
    format:
    dateStyle: long
    timeStyle: long

- openmeteo:
    label: Tienen, BE
    latitude: 50.815932
    longitude: 4.909615
    timezone: Europe/Brussels
    units: metric
    cache: 10